java_library(
    name = "ini_parser",
    srcs = glob([
        "java/**/*.java"
    ]),
    deps = [
        "@org_apache_commons_commons_lang3//jar"
    ],
    visibility = ["//visibility:public"]
)
