java_test(
    name = "IniParserTest",
    srcs = [
        "java/io/github/hcoona/parser/ini/IniParserTest.java"
    ],
    resources = glob([
        "resources/**"
    ]),
    size = "small",
    deps = [
        "//ini_parser/src/main:ini_parser",
        "@junit_junit//jar",
    ]
)
