java_library(
    name = "ini_config_flatten_processor",
    srcs = glob([
        "java/**/*.java"
    ]),
    deps = [
        "//config_flattener/src/main:config_flattener",
        "//ini_parser/src/main:ini_parser",
        "//file_processor/src/main:file_processor",
        "@org_slf4j_slf4j_api//jar",
        "@org_springframework_spring_core//jar"
    ],
    visibility = ["//visibility:public"]
)
