java_test(
    name = "ConfigurationFlattenerTest",
    srcs = [
        "java/io/github/hcoona/config_flattener/ConfigurationFlattenerTest.java"
    ],
    size = "small",
    deps = [
        "//config_flattener/src/main:config_flattener",
        "@org_springframework_spring_core//jar",
        "@junit_junit//jar"
    ]
)
