java_library(
    name = "file_processor",
    srcs = glob([
        "java/**/*.java"
    ]),
    deps = [
        "@org_apache_commons_commons_lang3//jar",
        "@commons_codec_commons_codec//jar",
        "@org_slf4j_slf4j_api//jar"
    ],
    visibility = ["//visibility:public"]
)
