package(
    default_visibility = ["//src:__subpackages__"]
)

java_library(
    name = "case_insensitive_string",
    srcs = [
        "CaseInsensitiveString.java",
    ],
    deps = [
        "@org_apache_commons_commons_lang3//jar",
    ],
)
