java_test(
    name = "AbstractProcessorTest",
    srcs = [
        "java/io/github/hcoona/file_processor/AbstractProcessorTest.java"
    ],
    size = "small",
    deps = [
        "//file_processor/src/main:file_processor",
        "@org_apache_commons_commons_lang3//jar",
        "@commons_codec_commons_codec//jar",
        "@junit_junit//jar",
        "@com_google_jimfs_jimfs//jar"
    ],
    runtime_deps = [
        "@com_google_guava_guava//jar"
    ]
)
